### ISSUE TITLE
new[] in rayMarching kernel

### ISSUE THREAD

**Issue by simesgreen** [nathanrgodwin/overfit-shapes#1]
Hi, I was searching for an implementation of this paper and came across your repo.

I was seeing corruption in the renderer, and noticed you were using new/delete in your rayMarching function in "kernel.cu". 

If you replace:
float* buffer = new float[2 * params.N];

with:
float buffer[2 * 32];

It fixes this. Allocating memory from the heap per thread like this is generally a bad idea for performance anyway.

Do you have any other trained models? Do you have instructions for running the training?

Thanks!

**Comment by nathanrgodwin** [comment]
@simesgreen It's been a while since I've used CUDA but I'm surprised that new/delete resulted in corruption in this case. Either way, this repo is still a bit of a work in progress and the new/delete is mostly a placeholder to get the renderer working until I have time to implement a better solution. Because the network shape can vary, allocating a fixed size array won't work in this case, so I was intending to replace the buffer with dynamically allocated shared memory eventually.

Unfortunately, I haven't had time to work on training other models. The easiest way to produce a training environment is to build the INSTALL project which will put all the libraries and scripts in the build/workspace folder.

After that you can just run:

    from NeuralImplicit import NeuralImplicit
    model = NeuralImplicit()
    model.encode(filename)

Although I can't guarantee that default settings will produce decent approximations for all input mesh.

You can also take a look at [OverfitShapes/train.py](https://github.com/nathanrgodwin/overfit-shapes/blob/main/OverfitShapes/train.py) to see a sample training and renderering script.
